### ISSUE TITLE
[Création de projet] "unknown or empty status"

### ISSUE THREAD

**Issue by KaeYuri** [KaeYuri/hub_intra_proto#10]
Quand on créer un projet, ce message apparaît

**Comment by pikanezi** [comment]
Normalement c'est fix

**Comment by KaeYuri** [comment]
[project.go:53] [E] Error 1146: Table 'intra_hub.promotion' doesn't exist

**Comment by pikanezi** [comment]
Regenere la base, j'ai rajoute des tables : ./intra-hub orm syncdb --force=true

**Comment by pikanezi** [comment]
Tu vas pouvoir reimporter les users ;)

**Comment by KaeYuri** [comment]
C'est OK :)
