### ISSUE TITLE
[Projet] Enlever etape "en attente de validation pedago" -> Flag

### ISSUE THREAD

**Issue by KaeYuri** [KaeYuri/hub_intra_proto#34]
Enlever l'étape du process, met mettre dans chaque projet un flag à trois valeur :

-> En attente de validation
-> OK
-> Blocage pédagogique

**Comment by KaeYuri** [comment]
Changement :

Le flag va sur les étudiants, non pas sur les projets

**Comment by pikanezi** [comment]
Normalement c'est fait
