### ISSUE TITLE
Page commentaire d'un projet

### ISSUE THREAD

**Issue by Hydhen** [KaeYuri/hub_intra_proto#40]
L'ajout d'un commentaire ce fait mais mauvais timestamp

Ex: Ajout le 20/07/2015 à 12h
Timstamp set au lundi 02 juillet 2006 15:04

**Comment by pikanezi** [comment]
Normalement c'est bon

**Comment by KaeYuri** [comment]
C'est toujours pas le bon temps, c'est 2h trop tôt

**Comment by pikanezi** [comment]
c'est bon

**Comment by KaeYuri** [comment]
Oep :)
