### ISSUE TITLE
Impossibilité de lancer un projet

### ISSUE THREAD

**Issue by Lokenstein** [KaeYuri/hub_intra_proto#51]
Hier, je me suis connectée, puis j'ai lancé un projet sans problème.
Ce matin, ayant fini de le rédiger, je voulais le poster mais le bouton ne réagissait pas, donc j'ai reload la page, et je suis arrivée sur ma page de login.
Après m'être loggée, j'ai voulu créer un projet, mais ça m'a renvoyé sur ma page de login, et ça a continué en boucle après plusieurs tests.
Toutes les autres pages semblent bien fonctionner.

**Comment by pikanezi** [comment]
Je close vu qu'on a vu le probleme ensemble :) hesite pas a refaire une issue si besoin
