### ISSUE TITLE
Besoin d'un export CSV stable

### ISSUE THREAD

**Issue by rlods** [KaeYuri/hub_intra_proto#53]

**Comment by pikanezi** [comment]
Pour l'instant j'ai fais un petit truc a l'arrache qui renvoie ca :

``` csv
id;nom du projet;description;Status;Manager;creation;mise a jour;nombre de membres;MembersName;skills;themes
1;Test;asasd;WAITING_MANAGER;neel_v;2015-07-20 11:13:12 +0000 UTC;2015-07-20 11:13:12 +0000 UTC;3;ohayon_m,etna_solign_e,solign_t;;
2;Another project;adasd;WAITING_MANAGER;;2015-07-20 11:54:46 +0000 UTC;2015-07-21 11:44:07 +0000 UTC;0;;;
```

Dis moi ce dont tu aurais besoin exactement :)

D'ailleurs quand il y a plusieurs valeurs, des champs separes par des virgules (comme les membres) ca te convient ou bof ?

**Comment by pikanezi** [comment]
http://ec2-52-18-1-134.eu-west-1.compute.amazonaws.com/export/projects

Faut que tu te log avant

**Comment by pikanezi** [comment]
http://ec2-52-18-1-134.eu-west-1.compute.amazonaws.com/export/projects c'est a peu pres bon ca ?
